Examen#1/FrontEnd/Models/DistritoViewModel.cs
namespace FrontEnd.Models
{
    public class DistritoViewModel
    {
        public int DistritoId { get; set; }

        public string Nombre { get; set; } = null!;
    }
}

Examen#1/FrontEnd/Models/ErrorViewModel.cs
namespace FrontEnd.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen#1/FrontEnd/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FrontEnd.Models
{
    public class LoginViewModel
    {


        [Required]
        [Display(Name = "Usuario")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }
        public bool RememberLogin { get; set; }
        public string? ReturnUrl { get; set; }

        public List<string>? roles { get; set; }

        public string? tokenString { get; set; }

    }
}

Examen#1/FrontEnd/Controllers/AccountController.cs
using FrontEnd.ApiModels;
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.CodeDom;
using System.Security.Claims;

namespace FrontEnd.Controllers
{
    public class AccountController : Controller
    {
        ISecurityHelper SecurityHelper;

        public AccountController(ISecurityHelper securityHelper)
        {
            this.SecurityHelper = securityHelper;
        }
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Login(string ReturneUrl = "/")
        {
            LoginViewModel user = new LoginViewModel();
            user.ReturnUrl = ReturneUrl;
            return View(user);

        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var url = user.ReturnUrl;
                    user = SecurityHelper.Login(user);
                    user.ReturnUrl = url;

                    HttpContext.Session.SetString("token", user.tokenString);



                    var claims = new List<Claim>() {
                                     new Claim(ClaimTypes.NameIdentifier, user.UserName as string),
                                         new Claim(ClaimTypes.Name, user.UserName as string)
                    };

                    foreach (var item in user.roles)
                    {
                        claims.Add(
                              new Claim(ClaimTypes.Role, item as string)

                            );
                    }




                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties()
                    {
                        IsPersistent = user.RememberLogin
                    });
                    //return View("AccessDenied");
                    return LocalRedirect(user.ReturnUrl);
                }

                return View(user);



            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

Examen#1/FrontEnd/Controllers/DistritoController.cs
using FrontEnd.Helpers.Interfaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class DistritoController : Controller
    {
        IDistritoHelper DistritoHelper;

        public DistritoController(IDistritoHelper distritoHelper)
        {
            DistritoHelper = distritoHelper;
        }


        // GET: DistritoController
        public ActionResult Index()
        {
            List<DistritoViewModel> lista = DistritoHelper.GetDistritos();
            return View(lista);
        }

        // GET: DistritoController/Details/5
        public ActionResult Details(int id)
        {
            DistritoHelper.Token = HttpContext.Session.GetString("token");

            DistritoViewModel distrito = DistritoHelper.GetDistrito(id);
            return View(distrito);
        }

        // GET: DistritoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DistritoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DistritoViewModel distrito)
        {
            try
            {
                DistritoHelper.AddDistrito(distrito);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DistritoController/Edit/5
        public ActionResult Edit(int id)
        {

            DistritoViewModel distrito = DistritoHelper.GetDistrito(id);
            return View(distrito);
        }

        // POST: DistritoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DistritoViewModel distrito)
        {
            try
            {
                DistritoHelper.UpdateDistrito(distrito);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DistritoController/Delete/5
        public ActionResult Delete(int id)
        {

            DistritoViewModel distrito = DistritoHelper.GetDistrito(id);
            return View(distrito);
        }

        // POST: DistritoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(DistritoViewModel distrito)
        {
            try
            {
                DistritoHelper.DeleteDistrito(distrito.DistritoId);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen#1/FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen#1/FrontEnd/Views/Distrito/Create.cshtml
@model FrontEnd.Models.DistritoViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DistritoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Examen#1/FrontEnd/Views/Distrito/Delete.cshtml
@model FrontEnd.Models.DistritoViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DistritoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DistritoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DistritoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    <form asp-action="Delete">
        @Html.HiddenFor(Model => Model.DistritoId)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Examen#1/FrontEnd/Views/Distrito/Details.cshtml
@model FrontEnd.Models.DistritoViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DistritoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DistritoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DistritoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DistritoId }) |



    <a asp-action="Index">Back to List</a>
</div>

Examen#1/FrontEnd/Views/Distrito/Edit.cshtml
@model FrontEnd.Models.DistritoViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DistritoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.HiddenFor(Model => Model.DistritoId)

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Examen#1/FrontEnd/Views/Distrito/Index.cshtml
@model IEnumerable<FrontEnd.Models. DistritoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DistritoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DistritoId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.DistritoId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.DistritoId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.DistritoId })
                </td>
            </tr>
        }
    </tbody>
</table>

Examen#1/FrontEnd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examen#1/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distrito" asp-action="Index">Distritos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>